[package]
name = "kindly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argv = "0.1.4"
libc = "0.2.107"
memsec = "0.6.0"
thiserror = "1.0.30"
rpassword = "5.0.1"
unixstring = "0.2.6"